#
# GitHub Actions: v20 - 最终路径修正版
#
name: Build ImmortalWrt for K2P (v20 - Path Fixed)

on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai
  REPO_URL: https://github.com/immortalwrt/immortalwrt.git
  REPO_BRANCH: master
  CONFIG_FILE: .config

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize build environment
      run: |
        # ... 省略和之前版本一样的 apt-get 安装命令 ...
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc; sudo -E apt-get update; sudo -E apt-get install -y build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget swig rsync libcrypt-dev python3-netifaces apk-tools; sudo -E apt-get autoremove --purge -y; sudo -E apt-get clean

    - name: Clone sources and prepare custom packages
      run: |
        git clone --depth 1 -b $REPO_BRANCH $REPO_URL openwrt
        
        mkdir -p openwrt/package/community

        git clone --depth 1 https://github.com/vernesong/OpenClash.git openwrt/package/community/openclash

        git clone --depth 1 https://github.com/kenzok8/openwrt-packages.git kenzok8_tmp
        
        echo "Copying required packages from kenzok8 feed..."
        # --- 【V20 核心修正】: 修正了 samba LuCI 界面包的正确文件夹名 ---
        cp -r kenzok8_tmp/luci-app-samba openwrt/package/community/
        cp -r kenzok8_tmp/samba4 openwrt/package/community/
        cp -r kenzok8_tmp/luci-app-aria2 openwrt/package/community/
        cp -r kenzok8_tmp/aria2 openwrt/package/community/
        cp -r kenzok8_tmp/ariang-nginx openwrt/package/community/
        
        rm -rf kenzok8_tmp

    - name: Cache downloaded sources (dl)
      uses: actions/cache@v4
      with:
        path: openwrt/dl
        key: ${{ runner.os }}-dl-${{ env.REPO_BRANCH }}-${{ hashFiles('openwrt/feeds.conf.default') }}

    - name: Update, install feeds and apply configuration
      run: |
        export TERM=dumb
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        cp ../.config .config
        sed -i 's/reg = <0xa0000 0xf60000>;/reg = <0xa0000 0x1f60000>;/' target/linux/ramips/dts/mt7621_phicomm_k2p.dts
        sed -i 's/IMAGE_SIZE := 15744k/IMAGE_SIZE := 32160k/' target/linux/ramips/image/mt7621.mk
        make defconfig

    - name: Compile the firmware
      run: |
        cd openwrt
        make -j$(nproc) V=s 2>&1 | tee build.log || (cat build.log && exit 1)
        
    - name: Consolidate packages and generate master index
      run: |
        APK_INDEX_TOOL=$(pwd)/openwrt/staging_dir/host/bin/apk
        UNIFIED_REPO_DIR=$(pwd)/openwrt/bin/unified_repo/mipsel_24kc
        mkdir -p $UNIFIED_REPO_DIR
        find openwrt/bin/packages/mipsel_24kc -name "*.apk" -exec cp {} $UNIFIED_REPO_DIR/ \;
        find openwrt/bin/targets/ramips/mt7621/packages -name "*.apk" -exec cp {} $UNIFIED_REPO_DIR/ \;
        cd $UNIFIED_REPO_DIR
        $APK_INDEX_TOOL index -o APKINDEX.tar.gz *.apk

    - name: Upload build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: immortalwrt-build-artifacts-${{ github.run_id }}
        path: |
          openwrt/bin/targets/ramips/mt7621/immortalwrt-ramips-mt7621-phicomm_k2p-squashfs-sysupgrade.bin
          openwrt/bin/unified_repo/
          openwrt/build.log
          openwrt/.config
