#
# GitHub Actions: 最终方案 · 权威实现版
#
name: Build ImmortalWrt for K2P (Authoritative Implementation)

on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai
  REPO_URL: https://github.com/你的用户名/immortalwrt.git
  REPO_BRANCH: openwrt-24.10
  CONFIG_FILE: .config

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize build environment
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get update
        sudo -E apt-get install -y build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget swig rsync libcrypt-dev python3-netifaces
        sudo -E apt-get autoremove --purge -y
        sudo -E apt-get clean

    - name: Clone Patched ImmortalWrt source
      run: |
        git clone --depth 1 -b $REPO_BRANCH $REPO_URL openwrt
        
    - name: Cache downloaded sources (dl)
      uses: actions/cache@v4
      with:
        path: openwrt/dl
        key: ${{ runner.os }}-dl-${{ env.REPO_BRANCH }}-${{ hashFiles('openwrt/feeds.conf.default')}}

    - name: Prepare build environment
      run: |
        export TERM=dumb
        cd openwrt
        cp ../.config .config
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
        make download -j$(nproc)

    - name: Compile main firmware
      id: compile
      run: |
        cd openwrt
        echo "Compiling firmware and packages..."
        make -j$(nproc) V=s 2>&1 | tee build.log || (grep -B 10 -A 30 -i "error" build.log && exit 1)
        echo "COMPILATION_STATUS=success" >> $GITHUB_ENV

    - name: Create Package Index and Keys
      # 只有在主编译成功后才执行此步骤
      if: env.COMPILATION_STATUS == 'success'
      run: |
        cd openwrt
        echo "Creating opkg package index..."
        # 使用单线程执行此关键步骤，以确保最大稳定性和最清晰的日志
        make package/index V=s
        
    - name: Upload Build Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: immortalwrt-build-artifacts-${{ github.run_id }}
        path: |
          openwrt/bin/targets/ramips/mt7621/
          openwrt/bin/packages/mipsel_24kc/
          openwrt/keys/
          openwrt/build.log
          openwrt/.config
