#
# GitHub Actions: v14 - 纯净官方版
#
name: Build ImmortalWrt for K2P (v14 - Pure Official)

on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai
  REPO_URL: https://github.com/immortalwrt/immortalwrt.git
  REPO_BRANCH: master # 我们依然使用 master，因为现在我们怀疑是 feed 冲突问题
  CONFIG_FILE: .config

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize build environment
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get update
        sudo -E apt-get install -y build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget swig rsync libcrypt-dev python3-netifaces
        sudo -E apt-get autoremove --purge -y
        sudo -E apt-get clean

    - name: Clone ImmortalWrt source
      run: |
        git clone --depth 1 -b $REPO_BRANCH $REPO_URL openwrt
        
    - name: Cache downloaded sources (dl)
      uses: actions/cache@v4
      with:
        path: openwrt/dl
        key: ${{ runner.os }}-dl-${{ env.REPO_BRANCH }}-${{ hashFiles('openwrt/feeds.conf.default') }}
        restore-keys: |
          ${{ runner.os }}-dl-${{ env.REPO_BRANCH }}-

    - name: Update, install feeds and apply configuration
      run: |
        export TERM=dumb
        cd openwrt
        # --- 【V14 核心修改】: 不再添加任何第三方源, 完全依赖官方 feeds ---
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        cp ../.config .config
        # 应用硬件修改
        sed -i 's/reg = <0xa0000 0xf60000>;/reg = <0xa0000 0x1f60000>;/' target/linux/ramips/dts/mt7621_phicomm_k2p.dts
        sed -i 's/IMAGE_SIZE := 15744k/IMAGE_SIZE := 32160k/' target/linux/ramips/image/mt7621.mk
        make defconfig

    - name: Compile the firmware
      run: |
        cd openwrt
        echo "Compiling firmware with multi-threading..."
        make -j$(nproc) V=s 2>&1 | tee build.log || (cat build.log && exit 1)
        
    - name: Upload build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: immortalwrt-build-artifacts-${{ github.run_id }}
        path: |
          openwrt/bin/targets/ramips/mt7621/
          openwrt/bin/packages/
          openwrt/build.log
          openwrt/.config
