#
# GitHub Actions: 最终方案 · 产物净化版
#
name: Build ImmortalWrt for K2P (Unsigned via Sanitization)

on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai
  # 关键修正: 指向你自己的、已经修改好硬件信息的仓库
  REPO_URL: https://github.com/murasamenomad/immortalwrt.git
  # 关键修正: 切换到 openwrt-24.10 稳定分支
  REPO_BRANCH: openwrt-24.10
  CONFIG_FILE: .config

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize build environment
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get update
        sudo -E apt-get install -y build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget swig rsync libcrypt-dev python3-netifaces
        sudo -E apt-get autoremove --purge -y
        sudo -E apt-get clean

    - name: Clone Patched ImmortalWrt source
      run: |
        # 只克隆你的主源码，不再需要 sed
        git clone --depth 1 -b $REPO_BRANCH $REPO_URL openwrt
        
    - name: Cache downloaded sources (dl)
      uses: actions/cache@v4
      with:
        path: openwrt/dl
        key: ${{ runner.os }}-dl-${{ env.REPO_BRANCH }}-${{ hashFiles('openwrt/feeds.conf.default')}}

    - name: Update, install feeds and apply configuration
      run: |
        export TERM=dumb
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        cp ../.config .config
        # .config 文件中 CONFIG_SIGNED_PACKAGES 已被注释，这会正确配置路由器端的 opkg
        make defconfig

    - name: Compile Firmware and Create Package Index
      run: |
        cd openwrt
        # 我们允许 make package/index 按其默认行为生成带签名的索引
        make -j$(nproc) V=s 2>&1 | tee build.log || (grep -B 5 -A 20 -i "error" build.log && exit 1)
        make package/index V=s
        
    - name: Sanitize Repository (Remove Signatures)
      run: |
        cd openwrt
        echo "Sanitizing package repository by removing all '.sig' files..."
        find ./bin/packages -type f -name "Packages.sig" -print -delete
        echo "Sanitization complete. Repository is now unsigned."

    - name: Upload Build Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: immortalwrt-build-artifacts-${{ github.run_id }}
        path: |
          openwrt/bin/targets/ramips/mt7621/
          openwrt/bin/packages/mipsel_24kc/
          # 不再需要上传 keys/ 目录，因为它不会被创建或已被净化
          # openwrt/keys/ 
          openwrt/build.log
          openwrt/.config
