name: Generate usign Signing Keys

on:
  # 允许您从 GitHub Actions 页面手动触发此工作流
  workflow_dispatch:

jobs:
  generate-keys:
    runs-on: ubuntu-latest
    steps:
      # 步骤 1: 安装编译 usign 所需的最基本依赖
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git libncurses5-dev libssl-dev

      # 步骤 2: 克隆 ImmortalWrt 源码
      - name: Clone ImmortalWrt source
        run: git clone --depth 1 https://github.com/immortalwrt/immortalwrt.git openwrt

      # 步骤 3: 编译构建系统中的 usign 工具
      # 这将生成我们需要的 usign 可执行文件
      - name: Build usign host tool
        run: |
          cd openwrt
          make tools/install

      # 步骤 4: 使用编译好的 usign 生成密钥对
      - name: Generate key pair
        run: |
         ./openwrt/staging_dir/host/bin/usign -G -p key-build.pub -s key-build
          echo "密钥对 key-build (私钥) 和 key-build.pub (公钥) 已成功生成。"

      # 步骤 5: 将生成的两个密钥文件作为产物上传 [1]
      - name: Upload keys as artifact
        uses: actions/upload-artifact@v4
        with:
          name: signing-keys
          path: |
            key-build
            key-build.pub
