name: 'Generate ImmortalWrt Signing Keys (branch: openwrt-24.10)'

on:
  workflow_dispatch: # Allow manual trigger from the Actions tab

jobs:
  generate-keys:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./openwrt

    steps:
      - name: 'Install Build Dependencies'
        working-directory: . # 在根目录执行
        run: |
          sudo apt-get update
          # 添加 libelf-dev 等一些常见的、可能被遗漏的依赖
          sudo apt-get install -y build-essential git libncurses5-dev libssl-dev ccache libelf-dev

      - name: 'Checkout ImmortalWrt Source on openwrt-24.10 branch'
        uses: actions/checkout@v4
        with:
          repository: 'immortalwrt/immortalwrt'
          ref: 'openwrt-24.10'
          path: 'openwrt'

      - name: 'Prepare Build Environment'
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig

      - name: 'Build Host Tools (including usign)'
        run: |
          # 使用 'V=s' 参数可以在出错时打印更详细的日志，帮助排查问题
          make tools/install -j$(nproc) V=s

      # --- 关键的调试步骤 ---
      - name: 'Verify usign Installation'
        run: |
          echo "Verifying if usign exists..."
          # 检查 usign 文件是否存在于预期路径
          if [ -f "./staging_dir/host/bin/usign" ]; then
            echo "SUCCESS: usign found at ./staging_dir/host/bin/usign"
            # 列出文件属性，确认其为可执行文件
            ls -l ./staging_dir/host/bin/usign
          else
            echo "ERROR: usign not found in ./staging_dir/host/bin/"
            echo "Listing contents of ./staging_dir/host/bin/ to debug:"
            # 如果文件不存在，列出该目录下的所有内容，帮助我们看到底生成了什么
            ls -l ./staging_dir/host/bin/
            # 以错误码退出，强制让工作流失败，而不是在下一步才失败
            exit 1
          fi

      - name: 'Generate Key Pair'
        run: |
          ./staging_dir/host/bin/usign -G -p key-build.pub -s key-build
          echo "Signing keys generated successfully in the 'openwrt' directory."

      - name: 'Upload Keys as Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-signing-keys-24.10
          path: |
            openwrt/key-build
            openwrt/key-build.pub
