name: Generate Persistent Signing Keys (Corrected)
on:
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone ImmortalWrt and prepare environment
        run: |
          git clone --depth 1 -b openwrt-24.10 https://github.com/immortalwrt/immortalwrt.git openwrt
          cd openwrt
          # 关键修正：创建一个最小化的 .config 来满足 make 的上下文要求
          echo "CONFIG_TARGET_ramips=y" > .config
          echo "CONFIG_TARGET_ramips_mt7621=y" >> .config
          echo "CONFIG_TARGET_ramips_mt7621_DEVICE_phicomm_k2p=y" >> .config
          make defconfig

      - name: Build usign tool
        run: |
          cd openwrt
          # 现在因为有了 .config 上下文，这个命令可以成功执行
          make tools/usign/compile

      - name: Generate and display new key pair
        run: |
          cd openwrt
          # 使用 usign 工具生成密钥对
          ./staging_dir/host/bin/usign -G -p my_key.pub -s my_key.key

          echo "========= PRIVATE KEY (my_key.key) - 请复制以下所有内容并保存 =========="
          cat my_key.key
          echo "========================================================================"
          echo ""
          echo "========= PUBLIC KEY (my_key.pub) - 请复制以下所有内容并保存 ==========="
          cat my_key.pub
          echo "========================================================================"
