name: 'Generate ImmortalWrt Signing Keys (branch: openwrt-24.10)'

on:
  workflow_dispatch: # Allow manual trigger from the Actions tab

jobs:
  generate-keys:
    runs-on: ubuntu-latest

    # 为此作业中的所有 'run' 命令设置默认工作目录
    defaults:
      run:
        working-directory: ./openwrt

    steps:
      - name: 'Install Build Dependencies'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git libncurses5-dev libssl-dev ccache
        # working-directory 不会应用于此步骤

      - name: 'Checkout ImmortalWrt Source on openwrt-24.10 branch'
        uses: actions/checkout@v4
        with:
          repository: 'immortalwrt/immortalwrt'
          # 使用 'ref' 参数来指定分支、标签或 commit SHA
          ref: 'openwrt-24.10'
          path: 'openwrt' # 将源码克隆到 openwrt 目录

      - name: 'Prepare Build Environment'
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig

      - name: 'Build Host Tools (including usign)'
        run: |
          make tools/install -j$(nproc) V=s

      - name: 'Generate Key Pair'
        run: |
          ./staging_dir/host/bin/usign -G -p key-build.pub -s key-build
          echo "Signing keys generated successfully in the 'openwrt' directory."

      - name: 'Upload Keys as Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-signing-keys-24.10
          path: |
            openwrt/key-build
            openwrt/key-build.pub
