name: Generate usign Signing Keys

on:
  # 允许您从 Actions 标签页手动触发此工作流
  workflow_dispatch:

env:
  # 将终端类型设置为 dumb，以防止在非交互式环境中出现问题
  TERM: dumb

jobs:
  generate-keys:
    runs-on: ubuntu-latest
    steps:
      # 步骤 1: 安装编译所需的基本依赖
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git libncurses5-dev libssl-dev

      # 步骤 2: 克隆 ImmortalWrt 源码
      - name: Clone ImmortalWrt source
        run: git clone --depth 1 https://github.com/immortalwrt/immortalwrt.git openwrt

      # 步骤 3: 准备构建环境
      # 此步骤更新并安装 feeds，然后创建默认的.config 文件
      - name: Prepare build environment
        run: |
          cd openwrt
         ./scripts/feeds update -a
         ./scripts/feeds install -a
          make defconfig

      # 步骤 4: 编译所有主机工具 (关键修复步骤)
      # 使用 'tools/install' 目标，这是一个更标准、更可靠的命令
      # 它会编译包括 usign 在内的所有构建所需的主机端工具
      - name: Build host tools (including usign)
        run: |
          cd openwrt
          make tools/install -j$(nproc) V=s

      # 步骤 5: 使用新编译的 usign 工具生成密钥对
      - name: Generate key pair
        run: |
          # 编译好的工具位于 staging_dir 目录中
         ./openwrt/staging_dir/host/bin/usign -G -p key-build.pub -s key-build
          echo "密钥对 key-build (私钥) 和 key-build.pub (公钥) 已成功生成。"

      # 步骤 6: 将生成的密钥文件作为产物上传，供您下载
      - name: Upload keys as artifact
        uses: actions/upload-artifact@v4
        with:
          name: signing-keys
          path: |
            key-build
            key-build.pub
