# .github/workflows/generate-keys.yml

name: 'Generate ImmortalWrt Signing Keys (Corrected for Debugging)'

on:
  workflow_dispatch:

jobs:
  generate-keys:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./openwrt

    steps:
      # 步骤 1: 安装依赖 (无变化)
      - name: 'Install Build Dependencies'
        working-directory: .
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses5-dev libssl-dev rsync \
            unzip zlib1g-dev file wget ccache libelf-dev

      # 步骤 2: 克隆源码 (无变化)
      - name: 'Checkout ImmortalWrt Source'
        uses: actions/checkout@v4
        with:
          repository: 'immortalwrt/immortalwrt'
          ref: 'openwrt-24.10'
          path: 'openwrt'

      # 步骤 3: 准备环境 (无变化)
      - name: 'Prepare Build Environment'
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig

      # 步骤 4: 编译工具链 (无变化)
      - name: 'Build and Install Toolchain & Host Tools'
        run: |
          make toolchain/install -j$(nproc) V=s

      # 步骤 5: 创建包索引 (关键修正：增加调试参数)
      - name: 'Create Package Index to Trigger Key Generation'
        run: |
          # 根据构建系统的建议，我们添加 -j1 V=s 参数来获取详细的错误日志
          # 这将准确地告诉我们是哪个环节导致了 "build failed"
          make package/index -j1 V=s

      # 步骤 6: 验证密钥 (如果上一步成功，此步会执行)
      - name: 'Verify and List Generated Keys'
        run: |
          echo "Verifying generated keys in 'key-build' directory..."
          if [ -d "key-build" ]; then
            echo "SUCCESS: 'key-build' directory found."
            echo "Listing contents:"
            ls -lR key-build
          else
            echo "ERROR: 'key-build' directory not found! Build process may have failed."
            exit 1
          fi

      # 步骤 7: 上传产物 (如果上一步成功，此步会执行)
      - name: 'Upload Keys as Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-signing-keys-24.10
          path: ./openwrt/key-build/
