# .github/workflows/generate-and-capture-keys.yml
name: 'ONCE-OFF: Generate and Capture Signing Keys'

on:
  workflow_dispatch: # 允许手动触发

jobs:
  generate_and_capture:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout ImmortalWrt Source'
        run: |
          git clone --depth 1 -b openwrt-24.10 https://github.com/immortalwrt/immortalwrt.git openwrt
          cd openwrt
          
      - name: 'Prepare Build Environment (Crucial Step)'
        working-directory: ./openwrt
        run: |
          # 更新并安装所有 feeds，这是生成完整 .config 的前提
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
          # 复制你的目标设备的默认配置作为基础
          # 这会生成一个完整的、非交互式的 .config 文件
          # 你可以根据你的设备修改 'defconfig_ramips_mt7621'
          cp defconfig_ramips_mt7621 .config
          
          # (可选但推荐) 确保所有依赖都满足
          make defconfig

      - name: 'Build Signing Tool and Generate Keys'
        working-directory: ./openwrt
        run: |
          # 这个命令会确保工具链和 usign 都被编译
          # 在这个过程中，由于 CONFIG_SIGNED_PACKAGES=y 默认存在，
          # 并且我们没有提供密钥，make 会自动为我们生成一套
          # 并放置在 <build_root>/keys/ 目录下
          make tools/usign/compile

      - name: 'Capture The Generated Keys'
        run: |
          # 将生成的密钥目录复制到一个临时区域，准备作为 Artifact 上传
          # 这是整个流程的核心！
          mkdir -p captured_keys
          cp -r openwrt/keys/* captured_keys/
          echo "Keys have been captured successfully. Listing contents:"
          ls -l captured_keys/

      - name: 'Upload Keys as Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-signing-keys
          path: captured_keys/
