# .github/workflows/generate-keys.yml

# 工作流名称
name: 'Generate ImmortalWrt Signing Keys (Corrected Syntax)'

# 触发条件：允许从 GitHub Actions 页面手动触发
on:
  workflow_dispatch:

jobs:
  # 定义一个名为 'generate-keys' 的作业
  generate-keys:
    # 在最新的 Ubuntu 虚拟机上运行
    runs-on: ubuntu-latest

    # 为此作业中的所有 'run' 命令设置默认的工作目录
    defaults:
      run:
        working-directory: ./openwrt

    steps:
      # 步骤 1: 安装编译所需的所有依赖
      - name: 'Install All Build Dependencies'
        # 覆盖默认工作目录，因为此时 './openwrt' 还不存在
        working-directory: .
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses5-dev libssl-dev rsync \
            unzip zlib1g-dev file wget ccache libelf-dev

      # 步骤 2: 克隆 ImmortalWrt 源码 (目标分支 openwrt-24.10)
      - name: 'Checkout ImmortalWrt Source'
        uses: actions/checkout@v4
        with:
          repository: 'immortalwrt/immortalwrt'
          ref: 'openwrt-24.10'
          path: 'openwrt'

      # 步骤 3: 准备构建环境 (非交互式构建的基础)
      - name: 'Prepare Build Environment'
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig

      # 步骤 4: 构建并安装工具链及所有主机工具 (关键修复)
      - name: 'Build and Install Toolchain & Host Tools'
        run: |
          make toolchain/install -j$(nproc) V=s

      # 步骤 5: 创建包索引以触发密钥生成
      - name: 'Create Package Index to Trigger Key Generation'
        run: |
          # 'make package/index' 会调用 usign，usign 发现没有密钥时会自动在 'key-build' 目录中生成
          make package/index V=s

      # --- 【核心修正】：将验证和上传拆分为两个独立的步骤 ---

      # 步骤 6: 验证生成的密钥 (用于调试和确认)
      - name: 'Verify Generated Keys'
        run: |
          echo "Verifying generated keys in 'key-build' directory..."
          if [ -d "key-build" ]; then
            echo "SUCCESS: 'key-build' directory found."
            echo "Listing contents:"
            ls -lR key-build
          else
            echo "ERROR: 'key-build' directory not found! Key generation failed."
            exit 1
          fi

      # 步骤 7: 将生成的密钥目录作为产物上传
      - name: 'Upload Keys as Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-signing-keys-24.10
          # 注意：这里的路径是相对于工作空间根目录的
          path: ./openwrt/key-build/
