name: Build ImmortalWrt for K2P

on:
  workflow_dispatch:
    inputs:
      ssh_action:
        description: 'SSH to the build runner to debug'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: master
  CONFIG_FILE: .config
  FIRMWARE_PATH: bin/targets/ramips/mt7621
  UPLOAD_FIRMWARE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Initialize Build Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget swig rsync
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean

    - name: Clone and Setup Source
      run: |
        git clone --depth 1 -b $REPO_BRANCH $REPO_URL openwrt
        
        # 应用硬件修改
        cd openwrt
        sed -i 's/reg = <0xa0000 0xf60000>;/reg = <0xa0000 0x1f60000>;/' target/linux/ramips/dts/mt7621_phicomm_k2p.dts
        sed -i 's/IMAGE_SIZE := 15744k/IMAGE_SIZE := 32160k/' target/linux/ramips/image/mt7621.mk

    - name: Configure and Build
      run: |
        cd openwrt
        
        # 应用自定义配置
        if [ -f "../$CONFIG_FILE" ]; then
          cp "../$CONFIG_FILE" .config
        fi
        
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
        make download -j$(nproc)
        make -j$(nproc) V=s

    - name: Package Firmware
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/${{ env.FIRMWARE_PATH }}
        rm -rf packages
        FIRMWARE_TAG=$(date +'%Y.%m.%d-%H%M')
        zip -r "immortalwrt-k2p-$FIRMWARE_TAG.zip" .
        echo "ZIP_PATH=$PWD/immortalwrt-k2p-$FIRMWARE_TAG.zip" >> $GITHUB_ENV

    - name: Upload Firmware Artifact
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      uses: actions/upload-artifact@v4
      with:
        name: immortalwrt-k2p-firmware
        path: ${{ env.ZIP_PATH }}
